### ISSUE TITLE
[Non-urgent] - Repo renaming suggestion

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-cloud#13]
Couple of thoughts to open the conversation,

- Maybe we could potentially rename this repo to `posthog-multitenancy` to better reflect its goal?
- Given that this repo is copyrighted and not open source, wouldn't it be better to make it private?

**Comment by Twixes** [comment]
I think this being open source (but all rights reserved) is fine, but I'd rename to `posthog-cloud` to accurately map it to our offering.

**Comment by paolodamico** [comment]
+1 on `posthog-cloud`. Regarding privacy I would argue that what's the point of this being public if all the rights are reserved? Not sure if anything good can come out of having this public (in theory by saying all rights reserved we're not allowing anyone to copy or use this code for anything at all)

**Comment by yakkomajuri** [comment]
Just found this issue. In my view having the Cloud code be open source adds to our transparency ethos. It's nice to know that even when you're in PostHog Cloud it isn't a black box, you can actually see what's going on and also see we don't do shady stuff.

Indeed it can potentially pose a security risk but one of the core principles of cybersecurity is that security shouldn't come through obscurity anyway.

**Comment by yakkomajuri** [comment]
Wondering if this needs a license though.

**Comment by paolodamico** [comment]
Quite old issue, but I think your argument is quite valid @yakkomajuri, in favor now of keeping this public, though I would still love to change the name to `posthog-cloud`, now that we're off Heroku, I think this might be easier? @fuziontech 

Re license IANAL but I don't think so, by default everything is copyrighted unless otherwise stated, and particularly our README does mention that the repo is copyrighted. CC @piemets

**Comment by piemets** [comment]
I have no opinion (nor the competence to offer one!) on whether we should make this open source or not, but use of PostHog Cloud is already covered by the [terms on our website](https://posthog.com/terms#posthog-cloud-license-terms). This covers everything to do with licensing, copyright etc.

So if we decide to go ahead with this, we can just add a line to the README that just says something like 'Your use of PostHog Cloud is subject to the terms linked here.' 

Side note - when I went to the README and tried to access the infra diagram, I saw two funky things:

![image](https://user-images.githubusercontent.com/70321811/108086446-49b14580-706e-11eb-94f5-71a9812a1938.png)

![image](https://user-images.githubusercontent.com/70321811/108086469-533aad80-706e-11eb-9517-4c45c5a2c120.png)

**Comment by paolodamico** [comment]
Just to clarify, we're not putting on the table whether this repo should be OSS or copyrighted, but rather knowing it's copyrighted, if we should add any licensing or other license-related clarification somewhere.

👍 Yup, issue already reported on #71, thanks!

**Comment by piemets** [comment]
Ah got it, sorry I think maybe some of the comments confused me here and I thought this was a conversation about making it OSS!

Yep in that case, I think just a minor edit to the README that says 'Your use of PostHog Cloud is subject to the terms [linked here](https://posthog.com/terms).' is fine, that covers everything including licensing and the copyright. 

Alternatively, if it is normal GitHub etiquette/practice to have a LICENSE file, then we could just create one that literally just contains that same single sentence as well. I wouldn't recommend that we write out the whole license again though, as we'll then need to maintain two copies of our terms in different places. But if you think users would be fine with just the README then no need to go with this option.

**Comment by fuziontech** [comment]
I'm 100% down for renaming this repo to posthog-cloud just on the grounds that it makes it super clear what the repo is for. Multi-tenancy sounds fancy and is technically correct, posthog-cloud is more clear.

**Comment by paolodamico** [comment]
This has been done
