### ISSUE TITLE
[Feature Request] Admin Dashboard Spec

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog-cloud#4]
**Current**
We use app.posthog to monitor user behavior as posthog is expected to do. Currently, we lack comprehensive metrics on all the different teams on posthog.

**Proposal**
I'm proposing to create a django app that adds an admin panel/section to our dashboard so that we can breakdown how teams are using our app and logging relevant metrics

List of teams and for each team: 
- events logged
- number of users per team
- number of actions/cohorts/dashboards/funnels per team (all the stuff we want to track for growth metrics)
- account status

This will be where we incorporate our billing management and status of each team in their trial period. 

**Additional**
Likewise, we will have to build in payment settings on the client facing app exclusively in posthog-production so that there isn't a whole irrelevant section for self-hosted users

**Comment by Twixes** [comment]
TBH I think this is solved by Metabase at the moment.

**Comment by fuziontech** [comment]
This ticket is going to have a birthday soon 🍰 
Should we say we are ok with Metabase and retire it @EDsCODE ? Or keep this alive as a potential future feature?

**Comment by paolodamico** [comment]
I think at least in terms of priorities, we can cover this with Metabase & Django Admin, so probably we won't need to work on this for a while.

**Comment by fuziontech** [comment]
Paolo! It had one day until it's birthday! How could you!! 🍰

**Comment by paolodamico** [comment]
😂😂😂happy coincidence!
