### ISSUE TITLE
Notes from dogfooding billing

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog-cloud#84]
I decided to move a side project of mine from usage analytics based on a Postgres table to PostHog. In doing so, I needed to create a second project (already having set up one side project), and therefore I was directed to "Upgrade Now" to get access to multiple features. I decided to try out premium for free-under-10k-events. That was pretty straightforward and clear.

I did experience a few pain points during billing setup itself though:

1. I clicked  "Subscribe now" (on the only available plan, Standard) on the billing page and was redirected to the Stripe page. Decided to immediately return to check plan details again, but all I could see was that according to PostHog I'd activated a plan and needed to set it up. Details have disappeared though, even the plan name.
As a user, my expectation was that some information on what I was supposed to pay for (besides event volume) would be there.
![plan-currently-inactive](https://user-images.githubusercontent.com/4550621/108674547-bf416980-74e5-11eb-9b92-0b6021be69aa.png)

2. ~~In any case, I decided to complete what I had already started and clicked "Finish setup". Unfortunately it's an internal React router link though, amd it did not redirect me to the Stripe page, leaving me with a 404. I got to Stripe after I refreshed the page, forcing a server hit.~~ Fixed by https://github.com/PostHog/posthog/pull/3416.
![broken-finish](https://user-images.githubusercontent.com/4550621/108675184-b7ce9000-74e6-11eb-94be-13e1e75f665e.png)

3. As a user, this initial charge of $0.50 was confusing to me. Will I get it back? This looks like a one-time thing, am I setting up monthly billing? Is this the standard plan? I could use a simple heads-up.
![card-auth](https://user-images.githubusercontent.com/4550621/108675373-02500c80-74e7-11eb-8735-96034c93f816.png)

4. As a minor UI thing, everything on billing setup status pages (success, problem etc.) is unusually large, giving a vibe disjointed from the rest of the product.
![status](https://user-images.githubusercontent.com/4550621/108675712-78547380-74e7-11eb-91b2-a45233fa00c7.png)

**Comment by Twixes** [comment]
One more thing:
I unliked my payment method and canceled subscription on the Stripe page. This however was **not reflected in the app at all**. Now I can't resume the subcription (not possible from within Stripe) and I also cancel it PostHog-side. I ended up in some sort of limbo – probably just getting usage out of PostHog for free, with PostHog having no clue.

**Comment by paolodamico** [comment]
This is super helpful! Thanks for taking the time to go through this and document it. Definitely want to work through all these bugs/improvements.

Just for context for everyone else on the last thing, while you end up in a UX limbo (which sucks and we need to address), your subscription is actually ended on our end when you cancel it on Stripe, so that means you would get at most the rest of your billing period of free usage (some tweaks are def needed here but not as dire), after which your billing account would be reset.

**Comment by paolodamico** [comment]
I think we can close this now with the new billing pages @Twixes, feel free to reopen if you disagree
